name: Backend

on:
  push:
    paths:
      - '.github/workflows/backend.yaml'
      - 'backend/**'

env: 
  PROJECT_ID: main-105
  SERVICE_NAME: backend
  REGION: us-central1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Build the Docker Image 
      run: docker build ./backend -t gcr.io/$PROJECT_ID/$SERVICE_NAME
    
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: ‘274.0.0’
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_105 }}
    
    - run: | 
        gcloud auth configure-docker
        gcloud config set run/platform managed
        gcloud config set run/region $REGION
        gcloud config set project $PROJECT_ID

    - name: Push image
      run: docker push gcr.io/$PROJECT_ID/$SERVICE_NAME
    
    - name: Cloud Run Deploy Backend
      run: |
           gcloud run deploy $SERVICE_NAME --image gcr.io/$PROJECT_ID/$SERVICE_NAME 