name: Cloud Endpoints

on:
  push:
    paths:
      - '.github/workflows/endpoints.yaml'
      - 'endpoints/**'

env: 
  PROJECT_ID: main-105
  SERVICE_NAME: backend
  API_GATEWAY: api-gateway-bf
  CONFIG_ID: 2020-01-20r0

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: ‘274.0.0’
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_105 }}
    
    - run: gcloud auth configure-docker
    
    - name: Deploy Initial API GW Service 
      run: |
        gcloud run deploy $API_GATEWAY --image="gcr.io/endpoints-release/endpoints-runtime-serverless:2" --allow-unauthenticated --project=$PROJECT_ID --platform=managed --region=us-central1
        
    - name: Set ENV vars
      run: | 
        echo "::set-env name=APIGW_HOST::$(gcloud run services describe $API_GATEWAY --format="value(status.url)" --region=us-central1 --project=$PROJECT_ID --platform=managed | sed -e 's#^https://##; s#/score/$##' )"
        echo "::set-env name=SERVICE_URL::$(gcloud run services describe $SERVICE_NAME --format="value(status.url)" --region=us-central1 --platform=managed --project=$PROJECT_ID)"
   
    - name: Echo ENV vars 
      run: |
        echo $SERVICE_URL
        echo $APIGW_HOST
        
    - name: Create OpenApi document
      run: |
        envsubst < ./endpoints/openapi-run_template.yaml > ./endpoints/openapi_conf.yaml
        cat ./endpoints/openapi_conf.yaml
        
    - name: Deploy Endpoint Service with config    
      run: |
        gcloud endpoints services deploy ./endpoints/openapi_conf.yaml --project=$PROJECT_ID

    - name: Create Custom API GW Image
      run: |
         ./endpoints/gcloud-build-image.sh -s $APIGW_HOST -c $CONFIG_ID -p $PROJECT_ID
    
    - name: Allow unauthenticated 
      run: |
        gcloud run services add-iam-policy-binding $API_GATEWAY \
        --member="allUsers" \
        --role="roles/run.invoker"

    - name: Deploy API GW Service With Custom Image
      run: |
        gcloud run deploy $API_GATEWAY --image="gcr.io/$PROJECT_ID/endpoints-runtime-serverless:$APIGW_HOST-$CONFIG_ID" --allow-unauthenticated --platform managed --project=$PROJECT_ID --region=us-central1
    