name: Frontend

on:
  push:
    paths:
      - '.github/workflows/frontend.yaml'
      - 'frontend/**'

env: 
  PROJECT_ID: main-104
  REGION: us-central1
  FRONTEND_IMG: frontend

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: ‘274.0.0’
        service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
  
    - run: gcloud auth configure-docker
    
    - name: Configure Firebase on the app side
      env: 
        AUTH_APIKEY: ${{ secrets.AUTH_APIKEY }}
      run: |
         envsubst < ./frontend/html/config_template.js > ./frontend/html/config.js 

    - name: Build the Docker image frontend
      run: docker build ./frontend -t gcr.io/$PROJECT_ID/$FRONTEND_IMG

    - name: Push image
      run: docker push gcr.io/$PROJECT_ID/$FRONTEND_IMG
  
    - name: Cloud Run Deploy Frontend
      run: |
        gcloud run deploy $FRONTEND_IMG \
          --project $PROJECT_ID \
          --image gcr.io/$PROJECT_ID/$FRONTEND_IMG \
          --allow-unauthenticated \
          --platform managed \
          --region us-central1 
    