name: Frontend

on:
  push:
    paths:
      - '.github/workflows/frontend.yaml'
      - 'frontend/**'

env: 
  PROJECT_ID: main-105
  REGION: us-central1
  FRONTEND_IMG: frontend

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: ‘274.0.0’
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_105 }}
  
    - run: | 
        gcloud auth configure-docker
        gcloud config set run/platform managed
        gcloud config set run/region $REGION
        gcloud config set project $PROJECT_ID
    
    - name: Configure Firebase on the app side
      env: 
        AUTH_APIKEY_105: ${{ secrets.AUTH_APIKEY_105 }}
      run: |
         envsubst < ./frontend/html/config_template.js > ./frontend/html/config.js 

    - name: Build the Docker image frontend
      run: docker build ./frontend -t gcr.io/$PROJECT_ID/$FRONTEND_IMG

    - name: Push image
      run: docker push gcr.io/$PROJECT_ID/$FRONTEND_IMG
  
    - name: Cloud Run Deploy Frontend
      run: |
        gcloud run deploy $FRONTEND_IMG --image gcr.io/$PROJECT_ID/$FRONTEND_IMG --allow-unauthenticated
    