name: Bucket

on:
  push:
    branches:
      - 'bucket-ci'

env: 
  PROJECT_ID: main-104
  BUCKET_NAME: ci-bucket-qipeit
  REGION: us-central1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: ‘274.0.0’
        service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
    
      
    - name: Create Bucket 
      run: |
        ./simpleserver/bucket_check.sh $PROJECT_ID $REGION $BUCKET_NAME 

    - name: Make bucket Publicly accesible 
      run: |
         gsutil acl ch -u AllUsers:R gs://$BUCKET_NAME/

    - name: Add files to the bucket 
      run: |
         gsutil cp -r ./web-site/ gs://$BUCKET_NAME/
    
    - name: Configure Firebase on the app side
      run: |
         echo "::set-env name=AUTH_APIKEY::${{ secrets.AUTH_APIKEY }}
         envsubst < ./web-site/config_template.js > ./web-site/config.js 