name: Test github actions

on:
  push


env: 
  PROJECT_ID: main-104
  SERVICE_NAME: gatewayv2
  API_GATEWAY: api-gateway-new

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: ‘274.0.0’
        service_account_key: ${{ secrets.SERVICE_ACCOUNT }}

    - name: bash
      run: |
        set -x
        sleep 2
        export
        sleep 2
        env
        sleep 2
        gcloud endpoints services list --project=main-104
        sleep 2
        gcloud endpoints services list --project=main-104 > testfile
        cat testfile
        sleep 2
        gcloud endpoints services describe api-gateway-new-estiec4hma-uc.a.run.app --project=main-104
        sleep 2
        gcloud endpoints services describe api-gateway-new-estiec4hma-uc.a.run.app --format="value(serviceConfig.id)" --project=main-104 > testfile2
        sleep 2
        cat testfile2
        echo '----------------------------------'
        
        
        
