name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Build the Docker Image 
      run: docker build simpleserver -t gcr.io/main-104/helloworld

#    - name: Push image
#      run: docker push gcr.io/main-104/helloworld
