name: Test github actions

on:
  push


env: 
  PROJECT_ID: main-104
  SERVICE_NAME: gatewayv2
  API_GATEWAY: api-gateway-new

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: bash
      run: |
        set -x
        export
        env
        gcloud endpoints services list --project=main-104
        
