name: 'Terraform GitHub Actions'
on:
  - push


jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '275.0.0'
          service_account_key: ${{ secrets.CI_CD_PIPELINE }}

      - run: |
          ls -la 
          pwd
      
      - name: Set Google GOOGLE_APPLICATION_CREDENTIALS
        run: |
          GOOGLE_APPLICATION_CREDENTIALS=$(echo ${{ secrets.CI_CD_PIPELINE}} | base64 -d)
          echo $GOOGLE_APPLICATION_CREDENTIALS > ./frontend-multi-tenant/terraform/key.json

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: './frontend-multi-tenant/terraform/'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: ./key.json

      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: './frontend-multi-tenant/terraform/'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: ./key.json

      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: './frontend-multi-tenant/terraform/'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: ./key.json

      - name: 'Terraform Apply'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: './frontend-multi-tenant/terraform/'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: ./key.json

      - name: 'Terraform Output'
        uses: hashicorp/terraform-github-actions@master
        id: terraform
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'output'
          tf_actions_working_dir: './frontend-multi-tenant/terraform/'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: ./key.json

      - name: 'Use Terraform Output'
        run: echo ${{ steps.terraform.outputs.tf_actions_output  }}
      