name: Deploy static site

on:
  push:
    paths: 
      - 'site/**'

env: 
  PROJECT_ID: main-104
  SITE_HOSTNAME: www.gcp.qipeit.com
  REGION: us-central
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: ‘274.0.0’
        service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
    
    - name: Create storage bucket if not exists
      run: |
        (gsutil ls -p ${PROJECT_ID} gs://${SITE_HOSTNAME})
        if [ -n "$?" ]; then
          gsutil mb -p ${PROJECT_ID} -l ${REGION} -c standard -b on gs://${SITE_HOSTNAME}
          gsutil iam ch allUsers:objectViewer gs://${SITE_HOSTNAME}
        fi


      
